// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADuoOasFHM3YJjB7R3OQ_vxlvfyhdl8Ng',
    appId: '1:991286749356:web:9164dde6c0b560b7af9709',
    messagingSenderId: '991286749356',
    projectId: 'kepuasanlayanan-e980a',
    authDomain: 'kepuasanlayanan-e980a.firebaseapp.com',
    storageBucket: 'kepuasanlayanan-e980a.firebasestorage.app',
    measurementId: 'G-B9MEZG9JG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2kvgXhcd7Vmhkv82Lv5thyt3vPLEgOdA',
    appId: '1:991286749356:android:0096c3759af1bbf6af9709',
    messagingSenderId: '991286749356',
    projectId: 'kepuasanlayanan-e980a',
    storageBucket: 'kepuasanlayanan-e980a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTj8oMr2QcyQMdvzfncgVsr73knuxhoA',
    appId: '1:991286749356:ios:9edb7fc7201e0d0baf9709',
    messagingSenderId: '991286749356',
    projectId: 'kepuasanlayanan-e980a',
    storageBucket: 'kepuasanlayanan-e980a.firebasestorage.app',
    iosBundleId: 'com.example.kepuasan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTj8oMr2QcyQMdvzfncgVsr73knuxhoA',
    appId: '1:991286749356:ios:9edb7fc7201e0d0baf9709',
    messagingSenderId: '991286749356',
    projectId: 'kepuasanlayanan-e980a',
    storageBucket: 'kepuasanlayanan-e980a.firebasestorage.app',
    iosBundleId: 'com.example.kepuasan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADuoOasFHM3YJjB7R3OQ_vxlvfyhdl8Ng',
    appId: '1:991286749356:web:ff6bcafa8c3d7302af9709',
    messagingSenderId: '991286749356',
    projectId: 'kepuasanlayanan-e980a',
    authDomain: 'kepuasanlayanan-e980a.firebaseapp.com',
    storageBucket: 'kepuasanlayanan-e980a.firebasestorage.app',
    measurementId: 'G-8WQ620X5FV',
  );
}
